name: continuous-integration

on:
  push:
    branches:
      - main
      - releases/*
  pull_request: null

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout SOOPERCOOL repository
        uses: actions/checkout@v7

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libgsl-dev libfftw3-dev libcfitsio-dev

      - name: Install uv & python
        uses: astral-sh/setup-uv@v10.1.0
        with:
          python-version: "3.13"

      - name: Install soopercool
        run: |
          uv venv
          uv pip install --group dev .

      - name: Lint
        run: uv run --no-sync flake8 --config .flake8

      - name: Tests
        run: uv run --no-sync pytest -vv --cov=soopercool
